allowed in-game reload and rtext based helpmsg
MCDReforged/LiteFileManager pull request #2
Opened 2021-05-01 11:50 UTC by ra1ny-yuki

2021-05-01 12:05 UTC, Fallen-Breath commented on LiteFileManager.py
> +§e{0} ls §61§r
建议此处不做修改，而是在 show_help 逻辑处理处进行判断，如可以在连续的 §7 结束后就退出循环

2021-05-01 12:07 UTC, Fallen-Breath commented on LiteFileManager.py
> +	'version': '1.0.2',
有新增功能，建议 1.1.0

2021-05-01 19:15 UTC, Fallen-Breath requested changes
见行间评论

2021-05-02 02:57 UTC, ra1ny-yuki commented
已完成修改

2021-05-02 07:54 UTC, Fallen-Breath approved these changes

2021-05-02 07:54 UTC, merged